"use client";

/**
 * Helpers for resolving the correct Privy wallet.
 *
 * GoodDollar verification and UBI claiming must use the embedded wallet
 * generated by Privy on sign-in (walletClientType === 'privy'), because
 * GoodDollar links identity to that specific key. External wallets
 * (MetaMask, WalletConnect) should NOT be used for GD operations.
 */

import type { ConnectedWallet } from "@privy-io/react-auth";
import { createWalletClient, custom } from "viem";
import { celo, celoAlfajores } from "viem/chains";

const CHAIN_ID = parseInt(process.env.NEXT_PUBLIC_CHAIN_ID ?? "44787");
export const ACTIVE_CHAIN = CHAIN_ID === 42220 ? celo : celoAlfajores;

/**
 * Returns the Privy embedded wallet from the wallets array.
 * Falls back to the first wallet if no embedded wallet is found.
 * Throws if no wallets are available at all.
 */
export function getEmbeddedWallet(wallets: ConnectedWallet[]): ConnectedWallet {
  const embedded = wallets.find((w) => w.walletClientType === "privy");
  const wallet = embedded ?? wallets[0];
  if (!wallet) throw new Error("No wallet found. Please sign in again.");
  return wallet;
}

/**
 * Builds a viem WalletClient from the Privy embedded wallet.
 * Used for GoodDollar identity + UBI claim operations.
 */
export async function buildEmbeddedViemClient(
  wallets: ConnectedWallet[],
  address: string
) {
  const wallet = getEmbeddedWallet(wallets);
  const provider = await wallet.getEthereumProvider();
  return createWalletClient({
    account: address as `0x${string}`,
    chain: ACTIVE_CHAIN,
    transport: custom(provider),
  });
}
